### ISSUE TITLE
[temporarily] removed older nifty* and fastfilters packages

### ISSUE THREAD

**Issue by k-dominik** [ilastik/publish-conda-stack#10]
This issue is related to switching the branches we use to build the respective packages

For nifty (nifty-with-gurobi, nifty-with-cplex) we have switched from the `stagged_rag` branch in our fork in ilastik, to the master branch in the original repo. In the Thorsten's repo the "highest" version tag that is reachable and that is picked up during conda build seems to be `0.3-beta`. This is not the newest tag (which is `0.18.1`), but it is picked up by conda build. In the `stagged_rag` branch, however, the "highest" version tag is `0.5`. In fastfilters the situation is somewhat similar. When packaging, conda will use the "highest" version tags for the environment, which, right now fails due to mixing gcc5 and non gcc5 built packages.

As a quick and dirty solution I have removed the "older" builds from ilastik-forge (after backing those up). I will reupload them, once I can discuss the issue with the respective repository owners.

**Comment by FynnBe** [comment]
public reminder to self: don't forget to clean package cache! for this hotfix to take effect!

**Comment by k-dominik** [comment]
okay I think this lost relevancy.
