### ISSUE TITLE
Support multi-output recipes

### ISSUE THREAD

**Issue by stuarteberg** [ilastik/publish-conda-stack#23]
Some recipes can produce multiple packages.  ([Here's an example.][1])  Currently, we don't upload all packages in that case.

[1]: https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml

**Comment by k-dominik** [comment]
good idea! Not that we would need it atm, but one would probably massage `get_rendered_version` a bit to return a tuple and add some loops here and there.. :)
